---
version: '3'
services:
  jenkins:
    image: 'rtyler/codevalet-master'
    ports:
      - 8080:8080
    environment:
      GITHUB_USERNAME: "${GITHUB}"

  webapp:
    image: 'ruby'
    user: ${UID:-1000}
    working_dir: ${PWD}
    ports:
      - 9292:9292
    environment:
      LANG: 'C.UTF-8'
      GEM_HOME: "${PWD}/vendor/gems"
      BUNDLE_PATH: "${PWD}/vendor/gems"
      BUNDLE_APP_CONFIG: "${PWD}/vendor/gems/.bundle"
      BUNDLE_DISABLE_SHARED_GEMS: 'true'
    command: 'bundle exec rackup -o 0.0.0.0'
