---
version: '3'
services:
  proxy:
    image: 'rtyler/codevalet-proxy:latest'
    ports:
      - 8000:80
      - 8443:443
    environment:
      - WEBAPP_SERVICE_PORT=9292
      - WEBAPP_SERVICE_HOST=webapp
    links:
      - webapp

  webapp:
    image: 'rtyler/codevalet-webapp:latest'
    ports:
      - 9292:9292
