---
version: '3'
services:
  proxy:
    image: 'rtyler/codevalet-proxy:latest'
    ports:
      - 8000:80
      - 8443:443
    environment:
      - WEBAPP_SERVICE_PORT=9292
      - WEBAPP_SERVICE_HOST=webapp
      # Example version of these variables for scripting/testing
      - JENKINS_CODEVALET_SERVICE_HOST=127.0.1.1
      - JENKINS_CODEVALET_SERVICE_PORT=80
    links:
      - webapp

  webapp:
    image: 'rtyler/codevalet-webapp:latest'
    ports:
      - 9292:9292
