---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium
  labels:
    kubernetes.io/cluster-service: 'true'
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/azure-disk
parameters:
  kind: 'Managed'
  storageaccounttype: 'Premium_LRS'
reclaimPolicy: Retain
