---
apiVersion: v1
kind: "List"
items:
  # jenkins
  - apiVersion: "v1"
    kind: "PersistentVolume"
    metadata:
      name: 'nginx'
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 50M
      gcePersistentDisk:
        pdName: 'nginx'
        fsType: ext4

  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: 'nginx'
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50M

  - apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      name: 'nginx'
      labels:
        name: 'nginx'
    spec:
      replicas: 3
      template:
        metadata:
          name: 'nginx'
          labels:
            name: 'nginx'
        spec:
          containers:
            - name: 'nginx'
              image: 'rtyler/codevalet-proxy:latest'
              imagePullPolicy: Always
              ports:
                - containerPort: 80
                - containerPort: 443
              env:
                - name: PRODUCTION
                  value: 'true'
                - name: LETSENCRYPT
                  value: 'true'
              volumeMounts:
                - name: 'nginx'
                  mountPath: '/etc/letsencrypt'
              livenessProbe:
                httpGet:
                  path: /
                  port: 443
                initialDelaySeconds: 30
                timeoutSeconds: 3
          volumes:
            - name: 'nginx'
              persistentVolumeClaim:
                claimName: 'nginx'

# vim: ft=yaml
