---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      name: 'webapp'
      labels:
        name: 'webapp'
    spec:
      replicas: 3
      template:
        metadata:
          name: 'webapp'
          labels:
            name: 'webapp'
        spec:
          containers:
            - name: 'webapp'
              image: 'rtyler/codevalet-webapp:latest'
              imagePullPolicy: Always
              ports:
                - containerPort: 9292
              env:
                - name: RACK_ENV
                  value: 'production'
                - name: PRODUCTION
                  value: 'true'
                - name: REDIRECT_URI
                  value: 'https://codevalet.io/github/authenticate'
                - name: GITHUB_CLIENT_ID
                  value: '790a28783a813e2b2b3c'
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: webapp
                      key: sentry
                - name: GITHUB_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: oauth
                      key: secret
              livenessProbe:
                httpGet:
                  path: /
                  port: 9292
                initialDelaySeconds: 30
                timeoutSeconds: 3

# vim: ft=yaml
