#!/bin/sh

exec docker run --rm -ti \
    -u $(id -u):$(id -g) \
    -w ${PWD} \
    -v ${PWD}:${PWD} \
    -e LANG=C.UTF-8 \
    -e GEM_HOME=${PWD}/vendor/gems \
    -e BUNDLE_PATH=${PWD}/vendor/gems \
    -e BUNDLE_APP_CONFIG=${PWD}/vendor/gems/.bundle \
    -e BUNDLE_DISABLE_SHARED_GEMS=true \
    -p 9292:9292 \
    ruby:2.3 $@
