#!/bin/sh

DOMAIN=codevalet.io
EMAIL=tyler--letsencrypt@monkeypox.org

while true; do

  if [ -d /etc/letsencrypt/live ]; then
    if [ ! -z ${LETSENCRYPT+x} ]; then
      echo ">> Let's Encrypt files appear to be on the filesystem";
      echo ">> .. attempting a renew";
      certbot renew -d ${DOMAIN} -m ${EMAIL} --agree-tos ;
    fi;
  else
    if [ ! -z ${LETSENCRYPT+x} ]; then
      echo ">> Let's Encrypt files do not appear to exist, registering"
      certbot nginx -d ${DOMAIN} -m ${EMAIL} --agree-tos;
    fi;
  fi;

  # Let's nap for a whole day!
  sleep 86400;
done;
