#!/bin/sh

DOMAIN=codevalet.io
EMAIL=tyler--codevalet@monkeypox.org

sleep 10

printenv

while true; do

  ls -lah /etc/letsencrypt
  cat /etc/letsencrypt/options-ssl-nginx.conf

  echo ">> Beep boop.."

  if [ ! "${LETSENCRYPT+x}" = "x" ]; then
    if [ -d /etc/letsencrypt/live ]; then
      echo ">> Let's Encrypt files appear to be on the filesystem";
      echo ">> .. attempting a renew";
      if [ $? -ne 0 ]; then
        certbot renew -n -d ${DOMAIN} -m ${EMAIL};
      fi;
    fi;
  else
    echo ">> Let's Encrypt files do not appear to exist, registering"
    certbot register -m ${EMAIL} --agree-tos;
    certbot certonly --webroot -w /usr/share/nginx/html -d ${DOMAIN} -m ${EMAIL} ;
  fi;

  echo ">> Snoozing for a while.."

  tail -n 500 /var/log/letsencrypt/*log
  # Let's nap for a whole day!
  sleep 3000
done;
