#!/bin/bash

REPOS_DIR=$PWD/build/repos
BASE_DIR=$(realpath $(dirname $0))
BUILDER_CONTAINER="rtyler/codevalet-builder"

mkdir -p $REPOS_DIR

function cloneWithDependencies() {
  if [ ! -d $1 ];  then
    git clone --depth 1 https://github.com/jenkinsci/$1.git
  fi;

  (cd $1 && ${BASE_DIR}/plugins-from-pom pom.xml)

  for plugin in $(cat $1/.plugins.txt); do
    echo ">> Must build dependency: $plugin";
    cloneWithDependencies "${plugin}-plugin"
  done;
}

pushd $REPOS_DIR

  cloneWithDependencies workflow-aggregator-plugin

  for plugin in *-plugin; do
    echo ">> Building $plugin"
    (cd  $plugin && \
      docker run --rm -ti -v $HOME/.m2:/root/.m2 \
      -v $PWD:/data -w /data ${BUILDER_CONTAINER} mvn install -DskipTests)
  done;

  for plugin in $(find . -iname "*.hpi" | grep -v "test-classes"); do
    cp $plugin ../plugins
  done;
popd
