#!/usr/bin/env python

import sys

from xml.etree.ElementTree import ElementTree


def main():
    document = ElementTree(file=sys.argv[1])
    plugins = []
    ns = {'mvn' : 'http://maven.apache.org/POM/4.0.0'}
    packaging = document.find('mvn:packaging', ns)

    if (packaging is not None) and (packaging.text == 'hpi'):
        for e in document.findall('mvn:dependencies', ns):
            for dep in list(e):
                scope = dep.find('mvn:scope', ns)
                if scope is None:
                    group = dep.find('mvn:groupId', ns).text
                    plugin = dep.find('mvn:artifactId', ns).text
                    is_plugin = False
                    try:
                        ['org.jvnet.hudson.plugins', 'org.jenkins-ci.plugins',
                                '${project.groupId}', 'io.jenkins.plugins',
                                'org.jenkins-ci.ui', 'org.jenkins-ci.plugins.workflow'].index(group)
                        is_plugin = True
                    except ValueError:
                        pass

                    # Let's only bother with dependencies that are actually Jenkins
                    # plugins :)
                    if is_plugin:
                        plugins.append(plugin)

    with open('.plugins.txt', 'w+') as fd:
        for plugin in plugins:
            fd.write(plugin)
            fd.write('\n')

if __name__ == '__main__':
    main()
