#!/bin/bash

mkdir build

OUTPUT_FILE=build/git-refs.txt

echo > $OUTPUT_FILE

for plugin in build/repos/*-plugin; do
    echo ">> Record HEAD for ${plugin}";
    SHA=$(cd $plugin && git rev-parse HEAD)
    echo "${plugin},${SHA}" >> $OUTPUT_FILE
done;
