#!/bin/sh

NAMESPACE=webapp
for pod in $(kubectl get pods --namespace=${NAMESPACE} -l app=webapp -o name); do
    echo ">> Terminating ${pod}"
    kubectl delete --namespace=${NAMESPACE} ${pod}
    # Sleep to allow Kubernetes to pull the latest image
done;
