#!/bin/sh

NAMESPACE=canary
for pod in $(kubectl get pods --namespace=${NAMESPACE} -l app=canary -o name); do
    echo ">> Terminating ${pod}"
    kubectl delete --namespace=${NAMESPACE} ${pod}
    # Sleep to allow Kubernetes to pull the latest image
    sleep 5
done;
